// <auto-generated />
using System;
using KurumsalGiderTakipSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KurumsalGiderTakipSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KurumsalGiderTakipSistemi.Models.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departmanlar");
                });

            modelBuilder.Entity("KurumsalGiderTakipSistemi.Models.Harcama", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FisYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HarcamaKategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HarcamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("RedNedeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("HarcamaKategoriId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Harcamalar");
                });

            modelBuilder.Entity("KurumsalGiderTakipSistemi.Models.HarcamaKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxLimit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("HarcamaKategorileri");
                });

            modelBuilder.Entity("KurumsalGiderTakipSistemi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TamAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("KurumsalGiderTakipSistemi.Models.Harcama", b =>
                {
                    b.HasOne("KurumsalGiderTakipSistemi.Models.HarcamaKategori", "HarcamaKategori")
                        .WithMany("Harcamalar")
                        .HasForeignKey("HarcamaKategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KurumsalGiderTakipSistemi.Models.Kullanici", "Kullanici")
                        .WithMany("Harcamalar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HarcamaKategori");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KurumsalGiderTakipSistemi.Models.Kullanici", b =>
                {
                    b.HasOne("KurumsalGiderTakipSistemi.Models.Departman", "Departman")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("DepartmanId");

                    b.Navigation("Departman");
                });

            modelBuilder.Entity("KurumsalGiderTakipSistemi.Models.Departman", b =>
                {
                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("KurumsalGiderTakipSistemi.Models.HarcamaKategori", b =>
                {
                    b.Navigation("Harcamalar");
                });

            modelBuilder.Entity("KurumsalGiderTakipSistemi.Models.Kullanici", b =>
                {
                    b.Navigation("Harcamalar");
                });
#pragma warning restore 612, 618
        }
    }
}
